ALTER TABLE students
ADD COLUMN IF NOT EXISTS class_level VARCHAR,
ADD COLUMN IF NOT EXISTS board VARCHAR,
ADD COLUMN IF NOT EXISTS stream VARCHAR,
ADD COLUMN IF NOT EXISTS science_group VARCHAR,
ADD COLUMN IF NOT EXISTS onboarding_complete BOOLEAN NOT NULL DEFAULT FALSE;
